name: Build ESPHome firmware

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build firmware (ESPHome CLI)
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/config \
            -it ghcr.io/esphome/esphome:latest \
            compile uart-bridge.yaml

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: .esphome/build/**/*.bin
