name: Build ESPHome firmware

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Compile ESPHome firmware
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/config \
            ghcr.io/esphome/esphome:latest \
            compile config.yaml
      
      - name: Find firmware
        run: |
          find . -name "*.bin"
      
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            **/*.bin
